///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/ambiental_13_A.aks
/// Generation time: mar 31 oct 2023 04:31:27 UTC
///

/// Song 'song_prueba' metadata macros
#define song_prueba_address  0x4000
#define song_prueba_size     216
#define song_prueba_end      0x40d7

/// Song 'song_prueba' array declaration
extern void song_prueba[song_prueba_size];
