///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/ambiental_13_A.aks
/// Generation time: mié 01 nov 2023 18:06:36 CET
///

/// Song 'song_prueba' metadata macros
#define song_prueba_address  0x4000
#define song_prueba_size     216
#define song_prueba_end      0x40d7

/// Song 'song_prueba' array declaration
extern void song_prueba[song_prueba_size];
