///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/prueba.aks
/// Generation time: dom 29 oct 2023 13:29:59 UTC
///

/// Song '_song_prueba' metadata macros
#define _song_prueba_address  0x4000
#define _song_prueba_size     140
#define _song_prueba_end      0x408b

/// Song '_song_prueba' array declaration
extern void _song_prueba[_song_prueba_size];
