///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/sfx.aks
/// Generation time: mié 01 nov 2023 20:09:04 CET
///

/// Song 'sfx' metadata macros
#define sfx_address  0x0117
#define sfx_size     151
#define sfx_end      0x1ad

/// Song 'sfx' array declaration
extern void sfx[sfx_size];
